### PR TITLE
add a dockerfile option for replication

### PR DESCRIPTION
**Pull request by paulfitz**
This adds a Dockerfile to flesh out a few loose steps for replication.  Existing docs were pretty great at nailing almost everything down.  For simplicity, tweaked plot to be saved in file rather than popped up.  Added python requirements to *requirements.txt files.

### CODE REVIEW

**Comment by paulfitz** [comment]
@chuckcho I added license information and brought in the mean cube file (for lack of a better place to put it).  Future cleanup could include per-source-file copyright and license statements, but I don't think the nature of the repo requires that level of cleaning at this time.

I don't know of any specific copyright policy yet so I used the default, employer gets copyright.  Let me know if that's a problem.

**Comment by chuckcho** [comment]
Everything looks good to me. Do you think auto test on Travis is an overkill as this won't be updated often?

**Comment by chuckcho** [comment]
tested this PR, and looks good! many thanks.

**Comment by paulfitz** [comment]
Thanks! Travis is a good idea, will do in follow-up, maybe not this week.

**Pull request merged**
